# Generated by Django 5.2.2 on 2025-06-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estacion', models.CharField(max_length=150)),
                ('tipo_estacion', models.CharField(max_length=150)),
                ('tech_area', models.CharField(max_length=150)),
            ],
        ),
    ]
