# Generated by Django 5.2.2 on 2025-06-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarma',
            name='activa',
            field=models.BooleanField(default=False),
        ),
    ]
